#!/bin/bash
# ------------------------------------------------------------------------
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Description:	Google Cloud Platform - Deployment Functions
# Version:			3.4
# Date:					12/September/2018
# ------------------------------------------------------------------------

DEPLOY_URL="https://storage.googleapis.com/sapdeploy"

## Import includes
source /dev/stdin <<< "$(curl -s ${DEPLOY_URL}/include/sap_func_main.sh)"
source /dev/stdin <<< "$(curl -s ${DEPLOY_URL}/include/sap_func_gcp.sh)"
source /dev/stdin <<< "$(curl -s ${DEPLOY_URL}/include/sap_func_maxdb.sh)"
source /dev/stdin <<< "$(curl -s ${DEPLOY_URL}/include/sap_func_nw.sh)"

### Base GCP and OS Configuration
main-get_os_version
gcp-install_gsdk /usr/local
main-set_boot_parameters
main-install_packages
main-config_ssh
gcp-get_settings
gcp-create_static_ip

## Prepare for MaxDB
maxdb-get_settings
maxdb-create_filesystems

## Prepare for NetWeaver
nw-install_agent
nw-create_filesystems

## clean up
main-complete
